language: php

sudo: false

env:
  global:
    - secure: "SC3+K5FQxVvvdqVLHNVQLOIHTizZYVcQYVFVkJTXatDiXrZlGvcW9ZtY6rrgp7R09feFiK8CpAD4+KkjaWsQz3n6FDxQVXlTsPS1Rf0K+WDzpUc/MiWY2TH6aY+dXKG/CT0H1JiBXxezaQw5zPXaM0hVzi6qbkuYZOJt18zL/haJp1cY9blWHh2e+YM9lnJojrdlCQumbY/PionPM+PLpFvgbJ0TYy/8UomuNAVNzhdH1vyHevHCllV7+riGJ1iANR0j1cE88eCU2tQek2dGkcmM+tYmQgCYIN8loBB3vAGKYFJSaI5fEbfpV/qzPwnPJo6M0a+mZPOyP50yesHvRgo5OtZwKnK0pMsz39MdTSylNd0oa3sUblRXMZlby/Z9jGpzm7BZwGQZ7+MaLuJxL9KT6LkWf4PAI0ALPcCOt9E98LhkqAqUzckW8/ccAMefapaJgOX7eHtLXv8Z+SqILKnzVzmR5ygBuYoExqsin5c5/LGz/CRucdEqeTSk9go3d0sf1HpEu6f2Nf+a4tpjQBgWYZAZHy+bp4ENCHPsu+32wydSOtKCxcCJEWLxO8rytZ1l6F9ypw8fAYJtdxHCojXubnT99WPXDEyNJWWUMo7S2ofaCFqBHpyWpjGvA2BHQ2thWH73MxvLepk4VI1TuCepKNt9OFLFW+ApmykjezA="
    - secure: "zto5D28Trbhul5JE4y1mIQchX2KI0uDCKvvRgJQ3fo3RFRypXzdFYU9U449bypqObvqvsAs9em7BVC8gaHwBUafXVxpPSkHtzrN4USEgZNcKm36tD37w/QBZ7Hgt4blv5MKWMoaQ6WQNOC4wv10CNAEIS3mLKiGZZ5gGKoURYUGyoWLTIl2gQM6FA3zx8U65XNc6OERngU33Bfr+btcyyjf4CTxybrRmNJeaeTg6qSOfuCRMkAMoGmO8OaKEoHz9v714zlWM/eOWYCpo0RDbOF2C01JwOiFVYuLpGrBEaAarK2CtfabIlNpQ2f/c+LGRQ7tfbKCPSfk9W6t4wwXVtkvr+BdrQbjefUnrUORzEE/qPoPX9k8u5+QXkXZR15vk0c7RYCFc6oPojMxiMepWtxEujTKHoK9E1WRJLKVazlq1H1NGn9rRrL8E5Vj7yLaqpQl/VnIPZp2hHFMR7PpkuIGeIVSB2LGu2ck/xU/S/UeKEAs/pqJGcZ1KqIL91cjMD6C2BdsmZR108zibXRWNeUAs202eXlSSlDvxgwgWPlmncLVbU5R2VaHnDST8zY3K/SlmT2p+i27Je4dUaBIJZSKYW2ZYn3x9+/Qc6+18YfQV2iYXtG7SBMrSLonIlGkjXC97oD9VM6RQoGnK7HiOEcqN78uVou6UjKN8l7OxCSQ="

matrix:
  include:
    - php: 5.5
    - php: 5.6
      env: COLLECT_COVERAGE=true CHECK_CS=true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - composer self-update
  - composer config github-oauth.github.com $GITHUB_TOKEN
  - composer validate

install:
  - composer install --prefer-dist

before_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then IS_MERGE_TO_MASTER=true; fi
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - if [[ "$COLLECT_COVERAGE" == "true" && "$IS_MERGE_TO_MASTER" == "true" ]]; then vendor/bin/phpunit --configuration=phpunit.xml --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit --configuration=phpunit.xml; fi
  - if [[ "$CHECK_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run; fi

after_success:
  - if [[ "$COLLECT_COVERAGE" == "true" && "$IS_MERGE_TO_MASTER" == "true" ]]; then vendor/bin/test-reporter; fi

notifications:
  email: false
