language: php

sudo: false

env:
  global:
    - secure: "eiGsHTdrm+36hrVZbajmU23eel4MoWNya3kkYnXx27Buy62VvuItMHoVs+83nwZAn8RgbMpnwf380dnPpX28ybgYnCEJV5pBwWD6YN7huWwBF4d5wstMynP3lOyZh/9L0ggH5ZcQlWk5RB2YZBfZQof+3j25aZOtUkFBBLeZz6bdnd7NKKNQxNtfBUxDW141zlqNYgiT/DhGbM9LhvrwSCa96INGhVoXIrV2112ApiEsoJM1Y7JMR0vBSzZ+OEI/mOFLErJtIjfsZYnWat2Z4K4aDhZUwo0dcQPNtCjUtj+E0HqLWaf3Bw2rpzCiqiX/WrJJavxp6ilLD97adlOH2dn0p56BeD9gWhD1+9BiOziQvxktpgUSC2E7gbGsJbrJNsAiOluLjFTLnjexhLYCm+ZLn0LH1A7v0ojV4xfdNg84NDFZ7tganhmNq52orLEJeuHKFGOsMP5ewqJIyV2xg0Yve8Sv0ZhIYg94HrzagSrJJ4+RI+g31Z7lXXAawx8qNskmAj4ZJe4BE3Kc6yqz5bHzw/koziC/i8Apyr+/jztKAYUlB4X6MWfa5YENSyBlK39B0il4eOGndYCOp4tMo1x03ylB+Ccj7OMZlZaOKdouccyevtgVPxjvJf2ysFgZXwEiEJbVRwbajnJjyk7LfoMY6U890qM/OtHgPfKqq84="
    - secure: "Bf2zZFs6JzUsSNujuqvHY/Gwfr71yafFnkwD7nLQSpURB23trrMIm6V3UN8m5/rcDRidESWJw0nLS7k3gZSGep7zNwpuETaQFoPOI/8iTDxe5yYHz4FA9ksP/D6EciS+w7E+f7TrFC/3emBjaFfC7AMxV5UOdxOvwnFqNPkjxPQjIiyDwAjbeQvcwMMEm5yai5jNEzSBqYAuHxz07kRBaHLC14avwnncBgLlZbWzJxprMZ59MYZQ5ttrBM9ORD6j1xfQY4IE40QXwNw0Rj0v4iOlRKbIOzkDzmUUfTA7QbYyf0r62yf9ItHQ08CReoqTOllwpc3eridwe8C5lYm2asktpeRKzXe5B77IEPx8G8vKD8JsZvZEOzznYa2zyy9nQTqGKVFsZh0it24WTbB2VVR+6QxwgS59+m4KSSg95wb9xiaMjoUIajDcuYpzoyY7ZiQD16Y/nilP8X57iKr9nNb6jJ6qJem+yJNuLpItrsaq+dYj2Y/siR5/2zPvg628PPAhZjArr0627sIXzppO5Z9n2glbtqS5pRM14+1hpnqomBYMO2diW9zh/pdNNrney9YedelrCzgWkc0kTlS2lj99kXDk0EYsoNkwdlLSpVzGu63b94BDIAQvbH9x69+uWQA/sHZGLwbfB7lonovKNP1mLqMCNMwehVc3tlc38aY="

matrix:
  include:
    - php: 5.5
    - php: 5.6
      env: COLLECT_COVERAGE=true CHECK_CS=true
    - php: 7
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - composer self-update
  - composer config github-oauth.github.com $GITHUB_TOKEN
  - composer validate

install:
  - composer install --prefer-dist

before_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then IS_MERGE_TO_MASTER=true; fi
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - if [[ "$COLLECT_COVERAGE" == "true" && "$IS_MERGE_TO_MASTER" == "true" ]]; then vendor/bin/phpunit --configuration=phpunit.xml --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit --configuration=phpunit.xml; fi
  - if [[ "$CHECK_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run; fi

after_success:
  - if [[ "$COLLECT_COVERAGE" == "true" && "$IS_MERGE_TO_MASTER" == "true" ]]; then vendor/bin/test-reporter; fi

notifications:
  email: false
